### PR TITLE
Add pangolin lineage determination process

### PR DESCRIPTION
**Pull request by koopmann**
just a draft

### CODE REVIEW

**Comment by priesgo** [comment]
big thanks @koopmann for this! I will be testing this PR this week.

**Comment by koopmann** [comment]
Concerning 2) i could successfully run this pipeline command on my local 
machine:

(base) 
***@***.***:/mnt/d/vm_shared_folder/src/covigator-ngs-pipeline$ 
./nextflow main.nf -profile test,conda --name hCoV-19_NTXX --output 
output/test4 --fasta test_data/hCoV-19_NTXX.fasta
N E X T F L O W  ~  version 21.04.3
Launching `main.nf` [lonely_marconi] - revision: 49c5fb5afe
executor >  local (4)
[69/8f830f] process > assemblyVariantCaller (hCoV-19_NTXX)        [100%] 
1 of 1 ✔
[0b/341dd1] process > pangolin (Lineage assignment with pangolin) [100%] 
1 of 1 ✔
[d1/7223a9] process > variantNormalization (hCoV-19_NTXX)         [100%] 
1 of 1 ✔
[19/94104a] process > variantSarsCov2Annotation (hCoV-19_NTXX)    [100%] 
1 of 1 ✔
Completed at: 17-Oct-2021 11:14:31
Duration    : 1m 20s
CPU hours   : (a few seconds)
Succeeded   : 4

My Conda env lists this packages after "conda env create -f 
environment.yml":
pango                     1.42.4               h69149e4_5    conda-forge
pangolearn                2021.08.24         pyh5e36f6f_0    bioconda
pangolin                  2.3.6                      py_0    bioconda


With the newest pangolin and downgrading biopython to 1.74 i could get 
it to run having this:

pango                     1.42.4               h69149e4_5    conda-forge
pango-designation         1.2.86             pyhdfd78af_0    bioconda
pangolearn                2021.09.28         pyh5e36f6f_0    bioconda
pangolin                  3.1.14             pyhdfd78af_0    bioconda

Keeping biopython at 1.79 with pinning to newest pangolin throws 
conflicts as you already have noticed...the only chance here would be to 
use e.g. a dockerized pangolin.

Best

Rudi



Am 2021-10-13 14:21, schrieb Pablo Riesgo-Ferreiro:

**Comment by koopmann** [comment]
In https://github.com/cov-lineages/pangolin/blob/master/environment.yml biopython is required to be 1.74..maybe we can ask if this could be changed to  - biopython>=1.74

**Comment by priesgo** [comment]
From the reading of the version releases (https://github.com/biopython/biopython/blob/master/NEWS.rst) since biopython 1.74 I see there have been quite some changes to the `Seq` object which we use for our variant calling over the FASTA file. I wonder if using 1.74 will affect either the results, the performance or both.

I will first ask to pangolin people as you suggest.

**Comment by priesgo** [comment]
Closing this as it was adressed in https://github.com/TRON-Bioinformatics/covigator-ngs-pipeline/pull/10

**Pull request closed without merging**
